### ISSUE TITLE
复制、粘贴功能

### ISSUE THREAD

**Issue by samyzhang** [weexteam/weex-ide#4]
复制、粘贴功能什么版本可以加入？好期待

**Comment by terrykingcha** [comment]
目前，这个ide用的CodeMirror，而其本身没有提供复制粘贴的功能，[CodeMirror的复制粘贴功能讨论](http://stackoverflow.com/questions/9492842/does-codemirror-provide-cut-copy-and-paste-api)，所以暂时应该有这个功能。
